#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check

# redirect:
#     path: /redirect
#     controller: App\Controller\RedirectController::index
